const Map<String, String> ar = {
  'accountNotFound':
      'تعذر العثور على حسابك. يرجى التحقق من المعلومات الخاصة بك',
  'accountExistsError': 'تعذر إنشاء الحساب لأن المستخدم موجود',
  'accountNotActivatedError':
      'لم يتم تفعيل حسابك بعد. سوف نرسل لك رمز التفعيل.',
  'actionDone': 'تمت',
  'activateBtn': 'تحقق',
  'activateTheAccount': 'تفعيل الحساب ',
  'addAddress': 'إضافة عنوان',
  'addAddressError':
      'لم يستطع النظام قراءة إحدي تلك المعلومات ( المدينه - اسم الحي - اسم الشارع) والتي تستخدمها نجده لأتمتة الخدمات المقدمه لكم. فضلا قم بتحريك الخريطه لاختيار موقع اخر',
  'addContract': 'إنشاء عقد',
  'addEvaluation': 'قم بالتقييم',
  'from': 'من',
  'failConfirmContract': 'فشل تأكيد العقد',
  'to': 'الى',
  'addNewComplaint': ' إضافة شكوى جديدة',
  'addPromoMoreThanOneWorker':
      'في حالة إضافة أكثر من عامل واحد ،يمكنك الحصول على خصم 10٪ للعمالة الثانية',
  'addToFavorites': 'الإضافة إلى المفضلة',
  'address': 'العنوان',
  'addressDeleteFailed': 'حدث خطأ أثناء حذف عنوانك.الرجاء إعادة  المحاولة.',
  'addressDeletedSuccessfully': 'تم حذف العنوان بنجاح',
  'addressDetails': 'تفاصيل العنوان',
  'addressFetchError': 'تعذر تحميل قائمة العناوين الرجاء إعادة المحاولة',
  'addressList': 'قائمة العناوين',
  'liveChat': 'محادثة نجدة الفورية',
  'addressUser': 'عنوان المستخدم',
  'afternoonContract': 'مساء',
  'afternoon': 'الفترة المسائية',
  'afternoonTime': 'مساءً',
  'dateBeforeFreeze': 'التاريخ قبل التجميد ',
  'dateAfterFreeze': 'التاريخ بعد التجميد ',
  'visitsAfterFreeze': 'الزيارات بعد التجميد ',
  'agree': 'موافق ',
  'agreeTermsAndConditions': 'اوافق على ',
  'alertConfirmLogout': 'هل أنت متأكد أنك تريد تسجيل الخروج?',
  'alertConfirmRemoveAccount':
      'تنبيه سوف يتم حذف الحساب من التطبيق نهائيا بما يحتويه من بيانات \nولا يمكن الرجوع اليها مره اخري',
  'deleteFavoriteMsg': 'هل أنت متأكد أنك تريد حذف العامل المفضل لديك',
  'deleteComplaintMsg': 'هل أنت متأكد أنك تريد حذف الشكوى؟',
  'deleteNotificationMsg': 'هل أنت متأكد أنك تريد حذف الاشعار ؟',
  'attendancePeriod': 'فترة الحضور',
  'awaitingResult': 'في انتظار النتيجة ...',
  'backToLogin': 'العودة لتسجيل الدخول',
  'bankAccountNumber': 'رقم الحساب البنكي',
  'bankAccountNumberRequired': ' رقم الحساب البنكي مطلوب',
  'bankName': 'إسم بنك',
  'bankNameRequired': 'إسم بنك مطلوب',
  'branchAddress': 'عنوان الفرع ',
  'branchLocationMap': 'موقع الفرع في الخريطة ',
  'branchPhoneNumber': 'رقم هاتف الفرع',
  'branchTitle': 'الفرع',
  'camera': 'كاميرا',
  'cancel': 'إلغاء',
  'cancelContract': 'إلغاء العقد',
  'cancelled': 'ملغاة ',
  'cannotTrackingStaff':
      'لا يمكنك تتبع السائق على الخريطة ، يمكنك الاتصال به عبر رقم هاتفه',
  'changeAccount': 'تسجيل الدخول بحساب آخر؟',
  'changeLanguage': 'تغيير اللغة',
  'changePassword': 'تغيير كلمة المرور',
  'changePasswordButton': 'تغيير كلمة المرور',
  'changePasswordError':
      'حدث خطأ أثناء تغيير كلمة المرور الخاصة بك. حاول مرة اخرى.',
  'changeWorker': 'إستبدال الكادر',
  'checkoutDelivery': 'تسليم خارج',
  'choose': 'أختر',
  'chooseAddressOnMap': 'تحديد الموقع على الخريطة',
  'chooseAddressOnMapEdit': 'تحديد الموقع على الخريطة ',
  'chooseBranchAddressOnMap':
      'لتأكيد اختيار الفرع برجاء الضغط على موقع الفرع على الخريطة',
  'chooseSystem': 'إختر النظام',
  'chooseSystemDescription':
      'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر.',
  'cityAddress': 'المدينة',
  'clickOnMapToAddAddress': 'انقر على الخريطة لإضافة العنوان',
  'close': 'غلق',
  'code': 'رمز',
  'codeVerifying': 'جارٍ التحقق من الرمز...',
  'complaint': 'الشكوى',
  'complaintDetails': 'تفاصيل الشكوى',
  'complaintSubject': 'موضوع الشكوى',
  'complaintSuccessDeleted': 'تم حذف الشكوى بنجاح',
  'complaints': 'الشكاوى',
  'complaintsIsRequired': 'محتوى الشكوى مطلوب',
  'complaintsListEmpty': ' قائمة الشكاوى فارغة',
  'confirm': 'تأكيد',
  'confirmPassword': 'تأكيد كلمة السر',
  'confirmPasswordInvalidError': 'يرجى التحقق من كلمات المرور',
  'confirmation': 'التأكيد',
  'confirmationCode': 'رمز التأكيد',
  'confirmed': 'نشط',
  'confirmedContract': ' العقود الحالية ',
  'confirmedRequest': 'مؤكدة',
  'contactUs': 'اتصل بنا',
  'contactUsTXt':
      'سعيدين بتقديم خدمتنا لك\nيمكنك التواصل معنا من خلال مواقعنا الالكترونيه',
  'deleteAddressMsg': 'هل أنت متأكد من حذف العنوان ؟',
  'contentDialogRefuseMission':
      'لا يمكنك الرفض المهمة إلا بعد إختيار سبب من أسباب الرفض المذكورة',
  'contractCreated': 'تم إنشاء العقد',
  'contractDetails': 'تفاصيل العقد',
  'contractList': 'قائمه العقود',
  'contractListFailure': 'فشل قائمة العقود',
  'contractName': 'عقد رقم ',
  'contractPeriod': 'مدة\nالتعاقد',
  'contractType': 'نوع العقد',
  'contractVisits': 'نظام الزيارات',
  'contracts': 'العقود ',
  'promoCodeText': 'كود الخصم ',
  'promoCodeExText': 'تطبيق كود الخصم ',
  'disAmountText': 'مبلغ الخصم',
  'disAmmTextValue': ' صافى المبلغ بعد الخصم ',
  'previousBalance': 'رصيد سابق ',
  'loyaltyBalance': 'رصيد نقاط الولاء',
  'rajhiAwards': 'خصم مكافآت الراجحي',
  'rajhiAwardsTitle': 'مكافآت الراجحي',
  'refundAwardsMsg': 'عزيزي العميل\n'
      'وفقا للسياسة الخاصه بمكافأت الراجحي نفيدكم بأنه يتم خصم رصيد مكافأت الراجحي بعد إدخال الكود المرسل إليكم من نظام مكافأت الراجحي.'
      '\nوفى حال عدم استكمال الاجرءات وسداد باقى المبلغ المستحق داخل تطبيق نجدة . يتم تحويل رصيد المكافأت الغير مستخدم إلى نقاط ولاء داخل تطبيق نجدة خلال 24 ساعه من تاريخ المعامله ويكون صالح للاستخدام لمدة 60 يوم. ولا يمكن إسترداد هذه المبالغ نقدا.',
  'loyaltyPoints': ' نقاط الولاء',
  'promoCodeApply': 'جارى تطبيق كود الخصم....',
  'notesText': 'ملاحظات',
  'selectAnotherPackText': 'اختيار باقة أخري',
  'cancelSelectedPackTxt': 'الغاء التحديد',
  'packContainTxt': 'تم اختيار باقة تحتوي علي',
  'whilePackContainTxt': 'زيارات في حين تم اختيار عدد',
  'specifyPackContainTxt': ' من الزيارات برجاء تحديد باقي الزيارات',
  'maxVisitValueText':
      'تم الوصول الي الحد الاقصي لعدد الزيارات يرجي الغاء اختيار الزيارات و التحديد من  جديد',
  'currentAppointment': 'الموعد الحالي',
  'currentAppointmentDialog': 'أيام  الزيارات الغير متاحة',
  'currentContract': 'العقود الحالية',
  'cv': 'بيانات السيرة الذاتية',
  'dateStartOfContract': ' تاريخ بدء العقد ',
  'dateStartOfResidentContract': 'تاريخ بدء العقد',
  'dedicate': 'إهداء',
  'dedicateVisit': 'إهداء زيارة',
  'delete': 'حذف',
  'deletePicture': 'حذف صورة',
  'deleting': 'الحذف قيد التقدم...',
  'deliverWorker': 'تم تسليم العامل إلى العميل',
  'delivery': 'توصيل',
  'deliveryChangeWorker': 'تسليم',
  'deliveryContract': 'توصيل',
  'deliveryMethod': 'طريقة التسليم',
  'deliveryState': 'حالة التوصيل',
  'deliveryTime': 'وقت التسليم',
  'deliveryTripType': 'توصيل',
  'dependsOnTheRequest': 'حسب الطلب ',
  'detailsVisitsWithoutPackage':
      'بالتفصيل طريقة حجز الكادر البشري لنظام الزيارة',
  'discardChangesQuestion': 'هل تريد إلغاء تعديلاتك ؟',
  'done': 'تم',
  'doneContract': ' العقود القديمة',
  'doneDelivery': 'تسليم',
  'donePickup': 'تم التوصيل',
  'doneTripState': 'منجزة',
  'downloadPdf': 'تحميل العقد ',
  'draft': 'مسودة',
  'draftRequest': ' في طور التنفيذ ',
  'draftMission': 'مجدول',
  'email': 'البريد الإلكتروني',
  'emailInvalidError': 'يرجى التأكد من إدخال بريد إلكتروني صحيح',
  'emptyDate': 'يرجى التأكد من اختيار التاريخ',
  'emptyFrequentlyQuestion': 'الأسئلة المتداولة فارغة',
  'emptyListOfAvailableWorker': 'قائمة فارغة بالعاملين المتاحين',
  'emptyNewsList': 'قائمة الأخبار فارغة.',
  'emptyFavoriteWorkers': ' الكوادر المفضلة فارغة',
  'enableBiometricsQuestion': 'هل ستمكّن مصادقة القياسات الحيوية؟',
  'endDate': 'تاريخ إنتهاء\nالعقد',
  'endMission': 'إنتهاء المهمة',
  'endTrip': 'إنهاء الرحلة',
  'endTripWarning': 'هل أنت متأكد أنك تريد إنهاء الرحلة?',
  'enterAddressName': 'اسم العنوان',
  'enterCityName': 'الحي',
  'enterStreetName': 'اسم الشارع',
  'enterYourCode': 'يرجى إدخال رمز التأكيد',
  'enterYourIdentityNumber': 'يرجى إدخال رقم هويتك',
  'enterYourPhoneNumber': 'يرجى إدخال رقم الهاتف الخاص بك',
  'enterZipCode': 'أدخل الرمز البريدي',
  'error': 'هناك خطأ ما',
  'errorAddressUsed': 'لا يمكنك حذف عنوان لأنه مستخدم في العقد',
  'errorFetchingWorkersList':
      'حدث خطأ أثناء تحميل قائمة العمال. يرجى  المحاولة  مرة اخرى.',
  'errorFoundDetailsAddress':
      'تعذر تحميل تفاصيل العنوان الرجاء إعادة المحاولة ',
  'errorDetectAddress': 'تعذر تحديد الموقع. الرجاء اختيار موقع آخر ',
  'evaluationInStore': 'تقييم التطبيق في المتجر',
  'experience': 'خبرة',
  'failAddingComplaint': 'فشل إضافة الشكوى',
  'failDeleteComplaint': 'فشل حذف الشكوى',
  'failDeleteNotification': 'فشل في حذف الاشعار ',
  'failToFreezeContract': 'فشل في إرسال طلب تجميد العقد',
  'failToSendTransferToBankAccount': 'فشل طلب  تحويل أموالك إلى حسابك المصرفي',
  'failUpdatingContract': 'فشل في تحديث العقد',
  'failedToLoadPortfolio': 'فشل تحميل المحفظة',
  'failedAction': 'عملية فاشلة',
  'failedContactUs': 'حدث خطأ أثناء إرسال الرسالة. يرجى  المحاولة  مرة اخرى.',
  'failedLoadFrequentlyQuestion': 'فشل تحميل الأسئلة المتداولة ',
  'failedSendRequestStaffReplacement': 'فشل في إرسال طلب استبدال الكادر ',
  'failedToLoad': 'فشل تحميل الخريطة',
  'failedToLoadData': 'فشل في تحميل البيانات',
  'noData': 'لا يوجد بيانات',
  'failedToLoadDetailsOfComplaint': 'فشل تحميل تفاصيل الشكوى',
  'failedToLoadListOfAvailableWorker': 'فشل في تحميل قائمة العامل المتاح',
  'failedToLoadListOfComplaint': 'فشل تحميل قائمة الشكاوى',
  'failedToLoadListOfNews': 'فشل تحميل قائمة الأخبار',
  'failedToLoadListPackages': 'فشل تحميل قائمة الباقات',
  'failedToLoadNotification': 'فشل تحميل قائمة الاشعارات',
  'failedToLoadPrivacyPolicy': 'فشل تحميل سياسة الخصوصية.',
  'failedToLoadRequestList': 'فشل تحميل قائمة الطلبات',
  'failedToLoadTermsAndConditions': 'فشل تحميل الشروط والأحكام.',
  'failFetchContractDetails': 'فشل إحضار تفاصيل العقد',
  'failureAddedAddress':
      'حدث خطأ أثناء إضافة العنوان. الرجاء إعادة  المحاولة. ',
  'failureCanceledContract': 'فشل إلغاء العقد',
  'failureCreatedContract': 'حدث خطأ أثناء إنشاء عقد',
  'rescheduleDone': 'تم إعادة جدولة الموعد بنجاح',
  'failureDownloadPdf': 'فشل تحميل pdf',
  'downloadAttachPdf': 'تحميل ',
  'downloadInvoices': 'تحميل الفاتورة ',
  'amountToPaid': 'المبلغ المستحق دفعه ',
  'chooseEmployee': 'اختيار عاملة ',
  'failureLoadedJobList': 'فشل تحميل قائمة المهام',
  'failureSponsorshipTransferContract': 'فشل إرسال طلب عقد نقل الكفالة',
  'favoriteWorkers': ' الكوادر المفضلة',
  'favouriteWorkerSuccessfullyDeleted': 'تم حذف العامل المفضل بنجاح',
  'female': 'أنثى',
  'finalPayment': ' إدفع الآن ',
  'finalPriceDetails': 'تفاصيل السعر النهائي',
  'checkOutBtn': 'المراجعة',
  'pleaseSelectLocation': 'يرجي تحديد العنوان الذي ترغب في استلام الخدمة فيه',
  'quesOneTxt': 'هل تمانع من إبراز تطبيق توكلنا قبل إستلام الخدمه؟',
  'quesTwoTxt':
      'هل يوجد بالمنزل أى شخص مصاب أو لديه اشتباه إصابة بفيرس كوفيد - 19؟',
  'quesThreeTxt':
      'هل يوجد كبار فى السن فوق الـ 65 سنه فى المنزل؟ او شخص مصاب بأمراض تنفسيه او أمراض مزمنه؟',
  'selectPeriod': 'قم باختيار الفترة (صباحي / مسائي)',
  'selectPeriodError': 'يرجى التأكد من اختيار الفترة',
  'selectWorkerError': 'يرجئ التأكد من اختيار العاملة',
  'finalPricing': 'التسعير النهائي',
  'freezeContract': 'تجميد العقد',
  'frozen': 'مجمد ',
  'frequentlyQuestions': ' الأسئلة المتداولة',
  'fromBranch': 'من الفرع',
  'fullName': 'الاسم الكامل',
  'gained': 'توفير',
  'gallery': 'صالة عرض',
  'gender': 'النوع',
  'generalTopics': 'المواضيع العامة',
  'getOff': 'نزول',
  'getOn': 'صعود',
  'goToRegisterBtn': 'انشاء حساب جديد',
  'greetings': 'مرحبا،',
  'haveAccountToBookAHuman':
      'يجب أن يكون لديك حساب لحجز كادر بشري لنظام المقيم',
  'haveAccountToViewListContract':
      'يجب أن يكون لديك حساب لعرض قائمة العقود الخاصة بك',
  'haveAccountToViewListNotification':
      'يجب أن يكون لديك حساب لعرض قائمة الاشعارات',
  'haveAccountToViewListProfile':
      'يجب أن يكون لديك حساب لعرض ملف التعريف الخاص بك',
  'height': 'الطول',
  'homeScreenTitle': 'الصفحة الرئيسية',
  'houseHold': 'معينة منزلية',
  'identity': 'رقم الهوية',
  'identityNumberShouldContainTenCharacters':
      'يجب أن يحتوي رقم الهوية على 10 أحرف',
  'inProgress': 'في تقدم',
  'inProgressCancel': 'نحن في صدد إستجابة على طلب إلغاء العقد ،الرجاء الانتظار',
  'inProgressChangeEmployee':
      'نحن في صدد إستجابة على طلب إستبدال الكادر ،الرجاء الانتظار',
  'inProgressFreeze':
      'نحن في صدد إستجابة على طلب تجميد العقد  ،الرجاء الانتظار ',
  'inProgressSponsorship':
      'نحن في صدد إستجابة على طلب نقل الكفالة  ،الرجاء الانتظار',
  'info': 'معلومات',
  'inputEmptyDropDownError': 'يرجى التأكد من اختيار عنصر',
  'internalServerError': 'خطأ في الخادم الداخلي',
  'internetNotFound': 'أنت غير متصل بالإنترنت ، تحقق من الاتصال وحاول مرة أخرى',
  'addressMustHaveAccount': 'يجب أن يكون لديك حساب لإضافة عنوان',
  'itemNationalitySA': 'سعودي (ة)',
  'itemNoNationalitySA': ' غير سعودي (ة) ',
  'job': 'المهنة',
  'listAvailableWorker': 'قائمة الكوادر المتوفرة',
  'listNotifications': 'قائمة الإشعارات',
  'listPackages': 'قائمة الباقات ',
  'loading': 'جار التحميل',
  'loadingDownloadingPdf': 'الجاري تحميل ...',
  'locationOnMap': 'الموقع على الخريطة',
  'attachment': 'المرفقات',
  'logIntoYourAccount': 'تسجيل الدخول إلى حسابك  ',
  'loginActivationError': 'يرجى التأكد من تفعيل حسابك قبل تسجيل الدخول',
  'loginError':
      'لا يمكن تسجيل الدخول ، يرجى التحقق من اسم المستخدم وكلمة المرور التي تم إدخالها',
  'loginLoading': 'تسجيل الدخول...',
  'makeChoice': 'اختر',
  'male': 'ذكر',
  'marital': 'الحالة الاجتماعية',
  'marriedStatus': 'متزوج(ة)',
  'message': 'يرجى كتابة رسالتك',
  'missionAddress': 'عنوان المهمة',
  'missionCity': 'مدينة ألمهمة',
  'missionDetails': 'تفاصيل المهمة',
  'missionEndHour': 'ساعة انتهاء المهمة',
  'missionList': 'المهام',
  'missionListFetchError': 'حدث خطأ أثناء تحميل قائمة المهام',
  'missionStartHour': 'ساعة بدء المهمة',
  'missionState': 'حالة المهمة ',
  'missionTime': 'وقت المهمة',
  'missionUpdateSucceeds': 'تم تحديث المهمة بنجاح',
  'month': 'شهر',
  'months': 'شهريًا',
  'morning': ' الفترة الصباحية',
  'morningContract': 'صباح',
  'morningTime': 'صباحا',
  'muslim': 'مسلم',
  'myRequests': 'طلباتي',
  'nationality': 'الجنسية',
  'newPeriod': 'الفترة الجديد',
  'newAppointment': 'الموعد الجديد',
  'daysNewAppointment': 'أيام الزيارات المتاحة',
  'newTripState': 'جديدة',
  'newUser': 'مستخدم جديد ؟',
  'helpCenter': 'مركز نجدة للمساعدة',
  'news': 'الأخبار',
  'next': 'التالى',
  'nextVisits': 'الزيارات القادمة',
  'no': 'لا',
  'noAddressFound': 'لا يوجد عناوين خاصة بك',
  'noContractFound': 'لا يوجد عقود',
  'noEmployee': 'لا يوجد موظف متوفر في هذا التاريخ',
  'capacityFull': 'السعة ممتلئة في هذا اليوم',
  'noInternetError': 'لا يوجد إنترنت الرجاء التحقق من اتصالك.',
  'noMissionFound': 'لم يتم العثور على أي  مهمة',
  'noRefuseReason': 'لم يتم العثور على قائمة أسباب الرفض',
  'noTripFound': 'لم يتم العثور على أي رحلة',
  'noWorkerFound':
      'لا تتوافر كوادر بشرية وفقا لاختياراتك. ستكون متاحة قريبا نأمل زيارتنا في وقت أخر  هل ترغب بالدفع و إنشاء العقد ؟ سيتم توفير الخدمة خلال 7 أيام أو قم بتسجيل طلبك و إشعارك في حال توفر الخدمة',
  'notMuslim': 'غير مسلم',
  'notificationEmpty': ' قائمة الإشعارات فارغة',
  'number': 'رقم الجوال',
  'numberError': 'يجب أن يحتوي رقم الهاتف على رمز البلد',
  'numberOfVisits': 'عدد الزيارات',
  'numberOfWorker': 'عدد العمالة المطلوبة',
  'ok': 'حسنا',
  'cicAndPhoneMissing': 'برجاء اضافة قيمة لل CIC او ادخال رقم الهاتف',
  'noListFreeze': 'لا يوجد زيارات للتجميد ',
  'updateVersion': 'يتوفر إصدار أحدث من التطبيق ، يرجى تحديثه الآن.',
  'packDetails': 'تفاصيل الباقة ',
  'contractSaved': 'تسجيل طلبك',
  'payAndCreate': 'الدفع وانشاء عقد',
  'saveAndCallYou': 'قم بتسجيل طلبك وسيتم اشعارك فى حال توفر الخدمه',
  'serviceIn7Days':
      'سيتم التواصل معكم بمجرد توافر الخدمه. وسوف يتم منحكم أولويه فى الخدمه ',
  'sorryNoDates': 'عفوا لا توجد مواعيد تسليم في ذلك التاريخ',
  'muslimFemale': 'مسلمة',
  'selectDate': 'اختيار التاريخ',
  'thanks': 'شكرًا لك ',
  'pack': 'الباقة ',
  'enterFreezeCode': 'يرجى كتابة رمز تفعيل طلب تجميد  العقد ',
  'visitsIsGift':
      'الزيارات بعد التاريخ الذي اخترته لا يمكن الغائها لانه تم اكتسابها من خلال نظام المكافأت أو الاهداءات. فضلا قم باعادة جدولة الزيارات المتبقيه بدلا من الغاء العقد',
  'visitsIsDone':
      'لا يمكن الغاء العقد لوجود زيارات تم تنفيذها أو تحت التنفيذ خلال التاريخ الذي اخترته ',
  'attention': 'برجاء الانتباه!!',
  'resendCode': 'اعادة ارسال الكود',
  'enterCancelCode': 'يرجى كتابة رمز تفعيل طلب الغاء العقد ',
  'oldContract': 'العقود القديمة',
  'ongoingTripState': 'حالية',
  'orderReceivedDelivery': 'استلام الطلب',
  'orderReceivedPickup': ' تم استلام الطلب',
  'password': 'كلمة السر',
  'passwordChangeNeeded': 'يجب عليك تغيير كلمة المرور الخاصة بك.',
  'passwordChangedSuccess': 'تم تغيير كلمة المرور الخاصة بك بنجاح.',
  'passwordInvalidError': 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
  'pay': 'الدفع',
  'paymentPage': 'صفحة الدفع',
  'personalPhoneNumber': 'رقم هاتف شخصي',
  'phoneNumber': 'رقم الهاتف',
  'phoneNumberError': 'يرجى التأكد من رقم الهاتف المدرج',
  'pickupContract': 'تسليم',
  'pickupState': 'حالة التسليم',
  'pickupTripType': 'إستلام',
  'pickupWorker': 'تم نقل العامل من العميل',
  'pleaseChoose': 'يرجى اختيار',
  'pleaseChooseSuspensionPeriod': 'الرجاء اختيار فترة تجميد  العقد',
  'pleaseEnterAddressName': 'يرجى إدخال اسم العنوان',
  'pleaseAcceptTerms': 'يرجى قراءة و الموافقة علي الشروط و الاحكام اولا!',
  'pleaseSelectPeriod': 'يرجي اختيار الفترة (الصباحيه / المسائيه)',
  'tryLaterContractMsg':
      'عفوا جميع الكوادر الحاليه مشغولة يرجي المحاولة مره اخري لاحقا',
  'pleaseEnterNameOfCity': 'يرجى إدخال الحي',
  'pleaseEnterNameOfStreet': 'الرجاء إدخال اسم الشارع',
  'pleaseEnterZipCode': 'يرجى إدخال الرمز البريدي',
  'portfolio': 'المحفظة',
  'postponementContract': 'طلب تأجيل العقد',
  'previousPlace': 'مكان العمل السابق',
  'previousVisits': 'الزيارات السابقة',
  'priceDetails': 'تفاصيل السعر',
  'privacyPolicy': 'سياسة الخصوصية',
  'profileEdit': 'الملف الشخصي',
  'questionSuspensionPeriod': 'ماهي فترة التجميد ?',
  'rate': 'تقييم',
  'readyPickup': ' جاهز للاستلام',
  'reasonRefuse': 'الأسباب رفض',
  'reasons': 'الأسباب',
  'reasonsCancelContract': 'أسباب إلغاء العقد',
  'reasonsSponsorshipTransferContract': 'أسباب نقل الكفالة',
  'recapRequest': 'مراجعة الطلب',
  'receivingMethod': 'طريقة الاستلام',
  'refusalRequestSentSuccessfully': 'تم إرسال طلبك بنجاح',
  'refusalDaysRequestSentSuccessfully': 'تم اختيار ايام الزيارات المتاحه بنجاح',
  'sorryAvailableDays':
      'عفوا نعتذر عن خدمتكم خلال المده المحدده نظرا لاننشغال كوادرنا في خدمة عملاء اخرين',
  'chooseDates': 'أيام الزيارات المختارة ',
  'sorryAvaDay': 'عذرا تم اختيار موعد غير متاح ',
  'selectedWorkSuccess': 'تم احتيار العاملة بنجاح',
  'refuseMission': 'رفض المهمة',
  'refusedMissionState': 'معفاة',
  'refusedRequest': 'مرفوضة',
  'registerBtn': 'إنشاء حساب جديد',
  'registering': 'جاري إنشاء الحساب',
  'religion': 'الديانة',
  'remainingDay': 'الأيام المتبقية',
  'renewContract': 'تجديد العقد ',
  'renewContractSameRequest': 'تجديد العقد بنفس الطلبات',
  'renewContractDifferentRequest': 'تجديد العقد مع الطلبات المختلفة',
  'requestListIsEmpty': 'قائمة الطلبات فارغة',
  'requestNumber': 'رقم الطلب',
  'requestPetition': 'طلب التماس',
  'requiredNationality': 'الجنسية المطلوبة',
  'rescheduleAppointment': 'إعادة جدولة الموعد',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'resetPasswordBtn': 'إعادة تعيين كلمة المرور',
  'resetPasswordSuccess':
      'تم إعادة تعيين كلمة المرور. سوف تتلقى رمز التفعيل حتى نتمكن من متابعة تغييرها',
  'resettingPassword': 'إعادة تعيين كلمة المرور الخاصة بك',
  'residenceContract': 'نظام  المقيمة',
  'retry': 'أعد المحاولة',
  'rs': 'ريال',
  'save': 'حفظ',
  'secondaryPhoneNumber': 'رقم هاتف ثانوي',
  'selectLocation': 'تحديد العنوان',
  'selections': 'الاختيارات',
  'send': 'إرسال',
  'serialNumber': 'رقم التسلسل : ',
  'servicePrice': 'سعر الخدمة بدون الضريبة',
  'settings': 'الإعدادات',
  'shareTheApp': 'شارك التطبيق',
  'singleStatus': 'عزباء/أعزب',
  'skills': 'المهارات',
  'skip': 'تخطى',
  'socialStatus': 'الحالة الاجتماعية',
  'sponsorshipTransfer': 'نقل الكفالة',
  'staffReplacement': 'طلب إستبدال الكادر',
  'startDate': 'تاريخ بدء\nالعقد',
  'startMission': 'بدء المهمة',
  'startTrip': 'انطلاق  الرحلة',
  'startTripWarning': 'واحد أو أكثر من العمال غير موجودين',
  'stateMethodDelivery': 'المرحلة',
  'stayInSystem': 'المقيمة',
  'stock': 'رصيدك لدى نجدة',
  'stock2': 'المبلغ المستحق سداده',
  'streetAddress': 'الشارع',
  'subjectComplaintIsRequired': ' موضوع الشكوى مطلوب',
  'submitCodeError': 'الرمز غير صحيح',
  'submitContract': 'طلب تقديم العقد',
  'subscriptionError': 'لا يمكن إنشاء حساب لخطأ داخلي. يرجى المحاولة مرة أخرى.',
  'rescheduleError417':
      'هذه الزيارة قريبة جدًا ، لذا لا يمكنك إعادة جدولة هذه الزيارة',
  'rescheduleError418': 'آسف. لا يمكنك تغيير الزيارة في نفس الوقت!',
  'rescheduleError404': 'لا يمكنك إعادة جدولة الزيارة التي انتهت',
  'rescheduleError421': 'عذرا الموظف الذي اخترته غير متوفر في هذا الوقت',
  'rescheduleError420':
      'نأسف لعدم تمكننا من خدمتك في هذا الوقت لأن جميع موظفينا مشغولون في هذا الوقت',
  'rescheduleError419':
      'الوقت الذي تختاره قريب جدًا ، لذا لا يمكننا خدمتك في الوقت الحالي ، يرجى تحديد وقت آخر',
  'subscriptionSuccess':
      ' تم إنشاء حسابك. سوف تتلقى رمز التفعيل حتى نتمكن من متابعة تفعيل حسابك',
  'successAddingComplaint': 'تمت إضافة الشكوى بنجاح',
  'successCanceledContract': 'تم إرسال طلب إلغاء العقد بنجاح',
  'successContactUs': 'تم إرسال طلبك بنجاح',
  'successDeleteNotification': 'تم حذف الاشعار بنجاح',
  'successSendRequestFreezeContract': 'تم بنجاح إرسال طلب تجميد العقد',
  'successSponsorshipTransferContract': 'تم إرسال الطلب نقل الكفالة  بنجاح',
  'successTransferToBankAccount':
      'تم طلب  تحويل أموالك بنجاح إلى حسابك المصرفي',
  'successUpdatingContract': 'تحديث العقد بنجاح',
  'successfullySentRequestOfChangeWorker': 'تم ارسال طلب تغيير عامل',
  'successfullyAddedAddress': 'تم إضافة العنوان بنجاح',
  'successfullyDownloadingPdf': 'تم تنزيل ملف pdf بنجاح',
  'system': 'نظام',
  'terms': 'أوافق على الشروط و الأحكام',
  'termsAndConditions': 'الشروط والأحكام',
  'contactUsVia': 'أتصل بنا عن طريق ',
  'termsIsNotSetError': 'يجب قبول الشروط والأحكام',
  'termsPopUpFooter': 'غلق',
  'termsPopUpHeader': 'الشروط و الاحكام',
  'timePeriod': 'الفترة الزمنية',
  'title': 'نجدة',
  'titleDeleteAddress': 'حذف عنوان',
  'topic': 'الموضوع',
  'topicIsRequired': 'يرجى كتابة موضوع',
  'totalAmount': 'المبلغ الإجمالي',
  'totalValue': ' إجمالى سعر الخدمه',
  'totalVisits': 'إجمالي عدد الزيارات',
  'trackStaffArrival': 'تتبع وصول الكادر',
  'transferToAccount': 'تحويل  إلى الحساب',
  'transferToBankAccount': 'تحويل  إلى الحساب البنكي',
  'tripDate': 'تاريخ الرحلة',
  'tripDetailsFetchError': 'حدث خطأ أثناء تحميل تفاصيل الرحلة',
  'tripListFetchError': 'حدث خطأ أثناء تحميل قائمة الرحلات',
  'tripMap': 'خريطة الرحلة',
  'tripStartHour': 'ساعة إنطلاق الرحلة',
  'tripState': 'حالة الرحلة',
  'tripUpdatedSuccess': 'تم تحديث الرحلة بنجاح',
  'trips': 'رحلات',
  'typeComplaint': 'نوع الشكوى',
  'typeComplaintsIsRequired': 'نوع الشكوى مطلوب',
  'unauthorisedError': 'لا يمكن تسجيل الدخول باستخدام هذا الحساب.',
  'update': 'تحديث',
  'updateBtn': 'تعديل',
  'updateContract': ' تعديل العقد',
  'updateMissionStateError': 'حدث خطأ أثناء تحديث حالة المهمة',
  'updateProfileError': 'لم نتمكن من تعديل ملفك الشخصي، يرجى المحاولة مرة أخرى',
  'updateProfileSuccess': 'تم تعديل ملفك الشخصي بنجاح',
  'updateTripStatusError': 'حدث خطأ أثناء تحديث حالة الرحلة',
  'updating': 'التحديث قيد التقدم...',
  'updatingData': 'جار التعديل...',
  'updatingMission': 'جارٍ تحديث المهمة...',
  'updatingTrip': 'جارٍ تحديث الرحلة...',
  'valueAddedTax': 'ضريبة القيمة المضافة',
  'verificationCodeError': 'يرجى التحقق من الرمز الذي تم إدخاله.',
  'verificationCodeInvalidError': 'يرجى التأكد من إدخال رمز التحقق الصحيح',
  'contract': 'عقد',
  'verificationSuccess': 'تم تفعيل حسابك بنجاح',
  'visit': 'زيارة',
  'visitContract': 'نظام الزيارات',
  'visitSystem': 'الزيارات',
  'txtVisiHome': '4 ساعات للزيارة',
  'txtStayInHome': '  اقامة دائمة ',
  'noContractHome': 'لا توجد عقود حالية أبدا الان واضف عقودك',
  'visitTime': 'وقت الزيارة',
  'visitDays': 'أيام الزيارة',
  'contractLink': 'العقد الإلكتروني',
  'paymentLink': 'الفاتورة الإلكترونية',
  'grateful': 'سعيدين بتقديم خدمتنا لك!!',
  'visitingStatus': 'حالة الزيارة',
  'visitor': 'زائر',
  'weeks': 'أسبوعيًا',
  'weight': 'الوزن',
  'workPhoneNumber': 'رقم هاتف العمل',
  'worker': 'الكادر',
  'workerCount': 'عدد العمال',
  'workingDays': 'أيام العمل',
  'workingTime': 'وقت العمل',
  'wrongVerificationCode':
      'لقد أدخلت رمز تحقق خاطئ. يرجى التحقق من الرمز المرسل.',
  'yes': 'نعم',
  'youCanSelectMaxSixVisits': '(يمكن إختيار من زيارة واحدة إلى ست زيارات)',
  'youCantAddAddress':
      'نعتذر عن خدمتكم. الموقع الذى تم إختياره خارج نطاق التغطيه الجغرافيه لخدماتنا فى الوقت الحالي',
  'youCanNotReschedule': 'لا يمكنك جدولة الزيارة',
  'zipAddress': 'العنوان البريدي',
  'zipCode': 'الرمز البريدي',
  'confirmedToNajdah': 'عقدك مؤكد لدي نجدة',
  'inputEmptyError': 'برجاء كتابة البيانات المطلوبة',
  'defaultRequestError': 'خطآ في إنشاء طلبك!',
  'goToContract': 'الذهاب للعقد',
  'continue': 'استرةمرار',
  'alert': 'إعلام',
  'getStarted': 'البدء',
  'currency': 'ريال',
  'monthly': 'شهريا',
  'week': 'اسبوع',
  'noPriceList': 'لا توجد اسعار',
  'errorFetchingPriceList': 'خطا اثناء عرض الاسعار',
  'checkout': 'الحساب',
  'cic': 'CIC',
  'youCannotReschedule': 'لا يمكن إعادة جدولة الزيارة',
  'youCanSchedule': 'يمكن الجدولة',
  'login': 'تسجيل الدخول',
  'logout': 'خروج',
  'gotoContractPage': 'الذهاب لصفحة العقد',
  'age': 'العمر',
  'approved': 'مؤكد',
  'review': 'المراجعة',
  'costSelectedWorker': 'التكلفة :',
  'warning': 'تنبية',
  'favorite': 'المفضلة',
  'wallet': 'المحفظة',
  'currentCredit': 'الرصيد الحالي',
  'expiryDate': 'تنتهي في',
  'favList': 'قائمة المفضلة',
  'remove': 'حذف',
  'noFavItem': 'قائمة المفضلة فارغة',
  'confirmRemoveEmployee':
      'هل أنت متأكد أنك تريد حذف هذا الموظف من قائمة المفضلة؟',
  'reload': 'إعادة تحميل',
  'noSlider': 'No Sliders found',
  'contractNum': 'رقم العقد',
  'viewContract': 'عرض العقد',
  'employee': 'موظف',
  'contactToDeliver': 'سنقوم بالتواصل معك لتقديم خدمة التوصيل',
  'rescheduleCosts': 'لاعادة الجدولة سيتم خصم مبلغ',
  'rateApp': 'تقييم التطبيق في المتجر',
  'enterUsername': 'ادخل اسم المستخدم',
  'completeProfile': 'اكمل بياناتك',
  'years': 'سنة',
  'amount': 'المبلغ',
  'pleaseEnterAmount': 'برجاء إدخال المبلغ',
  'visitsMenu': 'قائمة الزيارات',
  'homeWorker': 'عاملة منزلية',
  'maxNumValidVisits':
      'تم الوصول الي الحد الاقصي لعدد الزيارات يرجي إلغاء اختيار الزيارات و التحديد من جديد',
  'notAvaVisits': 'ايام الزيارات الغير متاحة',
  'avaVisits': 'ايام الزيارات  المتاحة',
  'addressPermission':
      'لم يستطع النظام قراءة عنوانك والتي تستخدمها نجده لأتمتة الخدمات المقدمه لكم. فضلا قم باعطاء امكانيه الوصول لعنوانك',
  'newDates': 'التواريخ الجديدة',
  'success': 'تم بنجاح',
  'freezeRescheduleNote': 'عدد الزيارات التي سيتم تأجيلها:',
  'freezeStartDate': 'تاريخ بداية تجميد العقد',
  'freezeEndDate': 'تاريخ إنتهاء تجميد العقد',
  'paymentFailed': 'فشلت عملية الدفع',
  'onBoarding1':
      'أهلا بكم فى تطبيق نجدة الحل الشامل لخدمات القوى العاملة فى المملكة السعودية ',
  'onBoarding2':
      'الكفاءة والاهتمام لاستقطاب القوى العاملة المدربة والمؤهلة لتلبية جميع احتياجاتك',
  'onBoarding3': 'اختر السيرة الذاتية المناسبة لك ولعائلتك',
  'onBoarding4': 'سهولة بادارة طلباتك والتحكم بعقود من مكان واحد',
  'visitState': 'حالة الزيارة',
  'active': 'نشط',
  'favoriteWorkerAdded': 'تم إضافة العامل إلى قائمة المفضلة بنجاح',
  'name': 'الأسم',
  'confirmToRemoveWorker1': 'هل انت متأكد من حذف ',
  'confirmToRemoveWorker2': 'من المفضلة؟',
  'unassigned': 'غير معين',
  'enterOTP': 'برجاء إدخال الـ OTP المرسل اليكم',
  'min': 'دقيقة',
  'sec': 'ثانية',
  'pleaseSelectImage': 'يرجى اختيار الصورة',
  'rateWorkerAdded': 'تم إضافة المراجعة الي العامل بنجاح',
  'noContracts': 'لا توجد عقود حالية ابدأ الان واضف عقودك!',
  'sureToCancelContract': 'هل أنت متأكد من إلغاء العقد؟',
  'pleaseWriteReasons': 'برجاء كتابة اسباب الإلغاء.',
  'news_not_found': 'لا توجد اخبار متاحه',
  'cancel_text_1': 'في حالة إلغاء العقد سوف يتم خصم رسوم إدارية بواقع',
  'cancel_text_2': 'عن كل زيارة متبقية في العقد.',
  'cancel_text_3': 'عدد الزيارات المتبقية',
  'cancel_text_4': 'وبالتالي تكون رسوم الإلغاء ',
  'cancel_text_5': 'وسوف يتم رد مبلغ',
  'cancel_text_6': 'إلى المحفظة الخاصة بكم داخل التطبيق',
  'cancel_request': 'طلب إلغاء العقد',
  'confirm_cancel_sms':
      'يرجى كتابة رمز تفعيل طلب إلغاء العقد الذي تم ارساله لهاتفك',
  'unknown_cancel_details': 'تكلفة إلغاء غير محددة',
  'refused': 'تم الرفض',
  'arrived': 'تم التوصيل',
  'get_in': 'تجهيز العاملة',
  'reward_error': 'لا يمكن نحديد نقاط الولاء',
  'number_not_found': 'الرقم غير موجود',
  'promoCodeTxtNotFound': 'رقم ال OTP غير موجود',
  'promoCodeAmountNotFound': 'قيمة مبلغ الخصم غير موجود',
  'un_authorized_message': "انتهت صلاحيه جلستك سيتم توجيهك الي تسجيل الدخول",
  'indonesia': 'إندونيسيا',
  'ethiopia': 'أثيوبيا',
  'uganda': 'أوغندا',
  'kenya': 'كينيا',
  'hours': 'ساعات',
  'for': 'لمدة',
  'notification': 'اشعار',
  'remove_user':'حذف الحساب'
};
