const Map<String, String> en = {
  'title': 'Najdah',
  'inputEmptyError': 'Please make sure to fill the required fields',
  'defaultRequestError':
      'Error occurred and could not perform your request. Please try later.',
  'ok': 'Ok',
  'goToContract': 'Go To Contract',
  'updateVersion':
      'There is a newer version of app available please update it now!',
  'sorryNoDates': 'Sorry, there are no delivery dates on that date',
  'resendCode': 'Resend Code',
  'enterCancelCode': 'Please type the activation code to cancel contract',
  'enterFreezeCode': 'Please type the activation code to freeze contract',
  'selectDate': 'Select Start Date',
  'yes': 'Yes',
  'confirmedToNajdah': 'Your contract is confirmed by Najdah',
  'thanks': 'Thank You',
  'pack': 'Pack',
  'attention': 'Attention!!',
  'visitsIsDone':
      'Contract can not be cancelled because there is ongoing missions during selected date',
  'visitsIsGift':
      'All Visits after the selected date can not be canceled once it was added through a reward system or gifts from friends. Kindly reschedule remaining visits instead of canceling it',
  'continue': 'Continue',
  'no': 'No',
  'loading': 'Loading',
  'inProgress': 'In progress',
  'deleting': 'Deleting...',
  'updating': 'Updating...',
  'inputEmptyDropDownError': 'Please make sure to choose an item',
  'noInternetError': 'No internet found please check your connection.',
  'retry': 'Retry',
  'delete': 'Delete',
  'alert': 'Alert',
  'info': 'Info',
  'accountNotFound':
      'Could not find this account. Please verify your identity number.',
  'unauthorisedError': 'Unauthorized!',
  'internalServerError': 'Internal Server Error',
  'accountNotActivatedError':
      'Your account is not activated yet. We will send you an activation code.',
  'rescheduleError417':
      'This visit is too near, So you can not reschedule this visit',
  'rescheduleError418': 'Sorry. You can not change visit to the same time!',
  'rescheduleError404': 'You can not reschedule a visit which is finished',
  'rescheduleError419':
      'The time you chose is too near so we can not serve you at this time please select another time',
  'rescheduleError420':
      'Sorry we can not serve you at this time because all of our staff is busy at this time',
  'rescheduleError421':
      'Sorry the employee you select is not available at this time',
  'subscriptionError':
      'Account could not be created for an internal error. Please try again.',
  'accountExistsError':
      'Account could not be created because user already exists',
  'wrongVerificationCode':
      'You provided a wrong verification code. Please verify the sent code.',
  'fullName': 'Full name',
  'identity': 'Identity',
  'number': 'Number',
  'email': 'Email',
  'password': 'Password',
  'confirmPassword': 'Confirm Password',
  'terms': 'Accept the Terms and Conditions',
  'termsPopUpHeader': 'Conditions',
  'termsPopUpFooter': 'Close',
  'numberError': 'Phone number should contain the country code',
  'phoneNumberError': 'Please make sure to provide a valid phone number',
  'emailInvalidError': 'Please make sure to enter a valid email',
  'passwordInvalidError': 'Password should contain at least 6 characters',
  'confirmPasswordInvalidError': 'Please verify password values',
  'termsIsNotSetError': 'Terms and conditions needs to be accepted',
  'subscriptionSuccess':
      'Congratulation, your account was created. You will receive an activation code so we can proceed to your account activation',
  'registerBtn': 'Sign Up',
  'registering': 'Registering your account',
  'checkOutBtn': 'Checkout',
  'noListFreeze': 'There is no available visits in this date',
  'selectPeriod': 'Please select the time Period (Morning / Afternoon)',
  'promoCodeText': 'Promo code',
  'promoCodeExText': 'Apply discount code?',
  'disAmmTextValue': 'Amount after discount',
  'previousBalance': 'Previous Balance',
  'promoCodeApply': 'Promo Code is Being Applied....',
  'loyaltyBalance': 'Loyalty Points Balance',
  'rajhiAwards': 'Rajhi Awards',
  'rajhiAwardsTitle': 'Rajhi Awards',
  'refundAwardsMsg': 'Dear Customer\n'
      'According to Al Rajhi rewards policy, we inform you that Al Rajhi rewards balance will be deducted after entering the code sent to you from the Al Rajhi rewards system.\n'
      'If the payment process is not completed and the remaining amount is not paid within Najdah application. The unused reward balance will be transferred to loyalty points within Najdah application within 24 hours from the date of the transaction and is valid for use for 60 days. These amounts cannot be refunded for cash.',
  'loyaltyPoints': 'Loyalty Points ',
  'disAmountText': 'Discount Amount',
  'notesText': 'Notes',
  'maxVisitValueText':
      'The maximum number of visits has been reached. Please deselect visits and select again',
  'selectAnotherPackText': 'Select Another Package',
  'cancelSelectedPackTxt': 'Deselect Visits',
  'packContainTxt': 'A Package Containing',
  'whilePackContainTxt': 'Visits while a number was selected',
  'specifyPackContainTxt':
      'from the visits please specify the remaining visits',
  'newUser': 'New User?',
  'loginLoading': 'Logging In...',
  'loginError':
      'Could not login, please verify the entered username and password',
  'loginActivationError':
      'Please make sure to activate your account before login',
  'goToRegisterBtn': 'Create New Account',
  'passwordChangeNeeded': 'You should change your password.',
  'cancel': 'Cancel',
  'settings': 'Settings',
  'changeAccount': 'Connect with another account?',
  'enableBiometricsQuestion': 'Would you enable biometrics authentication?',
  'error': 'Something Went Wrong!',
  'greetings': 'Welcome Back,',
  'enterYourIdentityNumber': 'Please Enter Your Identity Number',
  'enterYourPhoneNumber': 'Please enter your phone number',
  'resetPasswordBtn': 'Reset Password',
  'resetPasswordSuccess':
      'Your password has been reset. You will receive an activation code so we can proceed to your password change',
  'resettingPassword': 'Resetting your password',
  'confirmationCode': 'Confirmation code',
  'enterYourCode': 'Please enter your code',
  'verificationCodeError': 'Please verify the entered code.',
  'activateBtn': 'Verify',
  'codeVerifying': 'Verifying code...',
  'submitCodeError': 'Code is incorrect',
  'code': 'Code',
  'contract': 'Contract',
  'verificationSuccess': 'Congratulation, your account is activated',
  'verificationCodeInvalidError':
      'Please make sure to enter valid verification code',
  'passwordChangedSuccess': 'Your password was changed successfully.',
  'changePasswordButton': 'Change password',
  'changePasswordError':
      'Error occurred while changing your password. Please try again.',
  'profileEdit': 'Edit profile',
  'updateBtn': 'Update',
  'updateProfileSuccess': 'Your profile was updated successfully',
  'updateProfileError': 'Could not edit your profile, please try again',
  'update': 'Update',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'deletePicture': 'Delete Photo',
  'makeChoice': 'Make a choice',
  'personalPhoneNumber': 'Personal Phone Number',
  'workPhoneNumber': 'Work Phone Number',
  'marital': 'Marital',
  'nationality': 'Nationality',
  'itemNationalitySA': 'Saudi',
  'itemNoNationalitySA': 'Not a Saudi',
  'discardChangesQuestion': 'Do you want to discard your changes?',
  'updatingData': 'Updating...',
  'socialStatus': 'Social status',
  'gender': 'Gender',
  'pleaseChoose': 'Please choose',
  'male': 'Male',
  'female': 'Female',
  'singleStatus': 'Single',
  'marriedStatus': 'Married',
  'homeScreenTitle': 'Home',
  'noTripFound': 'No Trip found',
  'tripStartHour': 'Trip Start Hour',
  'tripDate': 'Trip date',
  'workerCount': 'Worker Count',
  'tripState': 'Trip state',
  'trips': 'Trips',
  'tripDetailsFetchError': 'Error occurred while fetching trip details',
  'tripListFetchError': 'Error occurred while fetching trip list',
  'updateTripStatusError': 'Error occurred while updating trip status',
  'endTripWarning': 'Are you sure you want to end the trip',
  'startTripWarning': 'One or more of the workers are not present',
  'startTrip': 'Start trip',
  'endTrip': 'End trip',
  'branchTitle': 'Branch',
  'getOn': 'Get on',
  'getOff': 'Get off',
  'updateMissionStateError': 'Error occurred while updating mission state',
  'newTripState': 'New',
  'ongoingTripState': 'Ongoing',
  'doneTripState': 'Done',
  'deliveryTripType': 'Delivery',
  'pickupTripType': 'Pickup',
  'missionListFetchError': 'Error occurred while fetching mission list',
  'noMissionFound': 'No Mission found',
  'missionAddress': 'Mission address',
  'missionCity': 'Mission city',
  'refusedMissionState': 'Refused',
  'missionList': 'Missions',
  'missionState': 'Mission state',
  'tripMap': 'Trip map',
  'updatingTrip': 'Updating trip',
  'updatingMission': 'Updating mission',
  'tripUpdatedSuccess': 'Trip updated successfully',
  'pickupWorker': 'The worker was taken from the customer',
  'deliverWorker': 'The worker was delivered to the customer',
  'addContract': 'New Contract',
  'contracts': 'Contracts',
  'missionDetails': 'Mission details',
  'missionTime': 'Mission time',
  'missionStartHour': 'Mission start hour',
  'missionEndHour': 'Mission End hour',
  'reasonRefuse': 'Reason refuse',
  'startMission': 'Start mission',
  'endMission': 'End mission',
  'refuseMission': 'Refuse mission',
  'contentDialogRefuseMission': 'Content Dialog refuse mission',
  'save': 'Save',
  'noRefuseReason': 'No refuse reason was found',
  'missionUpdateSucceeds': 'Mission updated successfully',
  'refusalRequestSentSuccessfully': 'Your request was sent successfully',
  'refusalDaysRequestSentSuccessfully':
      'You have successfully selected the available visiting days',
  'sorryAvailableDays':
      'We apologize for not serving you during the specified period because our staff is in the service of other customers',
  'chooseDates': 'Visits Dates Selected ',
  'sorryAvaDay': 'Sorry, an unavailable date has been selected',
  'requestPetition': 'Request Petition',
  'noAddressFound': 'No Address Found',
  'addressFetchError': 'Could not fetch your address list',
  'addressList': 'Address List',
  'liveChat': 'Live Chat',
  'addressDeletedSuccessfully': 'Address deleted successfully',
  'addressDeleteFailed':
      'Error occurred while deleting your address. Please try again.',
  'addressDetails': 'Address Details',
  'streetAddress': 'Street Address',
  'cityAddress': 'City Address',
  'zipAddress': 'Zip Address',
  'errorFoundDetailsAddress': 'Error Found Details Address',
  'errorDetectAddress':
      'Error with detecting the selected address. please pick another one',
  'titleDeleteAddress': 'Delete Address',
  'deleteAddressMsg': 'Are You Sure You Want To Delete Address ?',
  'secondaryPhoneNumber': 'Secondary phone number',
  'enterAddressName': 'Address name',
  'pleaseEnterAddressName': 'Please enter the address name',
  'pleaseAcceptTerms':
      'It is required to read and accept the Terms and Condition first',
  'pleaseSelectPeriod': 'Please select one of the provided period',
  'tryLaterContractMsg':
      'Sorry! all employee are busy. please tray again later.',
  'enterStreetName': 'Street address',
  'pleaseEnterNameOfStreet': 'Please enter the street address',
  'enterCityName': 'City',
  'pleaseEnterNameOfCity': 'Please enter the City',
  'zipCode': 'Zip code',
  'pleaseEnterZipCode': 'Please enter the zip code',
  'skip': 'Skip',
  'done': 'Done',
  'getStarted': 'Get Started',
  'next': 'Next',
  'successfullyAddedAddress': 'Successfully Added Address',
  'failureAddedAddress': 'Failure Added Address',
  'enterZipCode': 'Enter Zip Code',
  'startDate': 'Start\nDate',
  'endDate': 'End\nDate',
  'attendancePeriod': 'Attendance Period',
  'receivingMethod': 'Receiving Method',
  'totalAmount': 'Total Amount',
  'addAddress': 'Add address',
  'addAddressError':
      'System could not read one of this information from maps (city - district - street name ) which Najdah use to automate service delivery, kindly move the map to select another location',
  'clickOnMapToAddAddress': 'Click on the Map to Add Address',
  'confirmedContract': 'Confirmed Contract',
  'doneContract': 'Previous Contracts',
  'morningContract': 'Morning Contracts',
  'afternoonContract': 'Afternoon Contract',
  'deliveryContract': 'Delivery Contract',
  'pickupContract': 'Pickup Contracts',
  'residenceContract': 'Residence Contracts',
  'visitContract': 'Visits Contracts',
  'noContractFound': 'No Contracts Found',
  'contractListFailure': 'Failed to load contract list!',
  'chooseSystem': 'Choose the system',
  'chooseSystemDescription':
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s',
  'system': 'System',
  'txtVisiHome': '4 Hours per\nVisit',
  'txtStayInHome': 'Permanent\nResidence',
  'noContractHome':
      'There are no existing contracts, start now and add your contracts',
  'visitSystem': 'Visits',
  'stayInSystem': 'Stay-In',
  'contractList': 'Contract List',
  'contractName': 'Contract Name',
  'contractType': 'Contract Type',
  'totalVisits': 'Total Visits',
  'addressUser': 'Address User',
  'oldContract': 'Old Contracts',
  'currentContract': 'Current Contracts',
  'contractDetails': 'Contract Details',
  'stateMethodDelivery': 'State Method of Delivery',
  'branchLocationMap': 'Branch Location on map',
  'trackStaffArrival': 'Track Staff Arrival',
  'updateContract': 'Update Contract',
  'contractPeriod': 'Contract Period',
  'cancelContract': 'Cancel Contract',
  'staffReplacement': 'Staff Replacement',
  'postponementContract': 'Postponement Contract',
  'freezeContract': 'Freeze Contract',
  'submitContract': 'Submit Contract',
  'sponsorshipTransfer': 'Sponsorship Transfer',
  'attachment': 'Attachments',
  'failFetchContractDetails': 'Fetching Contract Details Failed',
  'locationOnMap': 'Location on map',
  'loadingDownloadingPdf': 'Loading the PDF file',
  'successfullyDownloadingPdf': 'Successfully downloaded the PDF file',
  'failureDownloadPdf': 'Failed to Download the PDF file',
  'nextVisits': 'Upcoming Visits',
  'previousVisits': 'Previous Visits',
  'religion': 'Religion',
  'experience': 'Experience',
  'remainingDay': 'Remaining Day',
  'currency': 'SAR',
  'contractVisits': 'Contract Visits',
  'selectLocation': 'Select Location',
  'selections': 'Selections',
  'timePeriod': 'Time Period',
  'contractLink': 'Contract link',
  'paymentLink': 'Payment Link',
  'grateful': 'We are grateful to provide you with our services!!',
  'numberOfVisits': 'Number of Visits',
  'youCanSelectMaxSixVisits': 'You can select Select Max Six visits',
  'dateStartOfContract': 'Start date of the Contract',
  'dateStartOfResidentContract': 'Start date of the Contract',
  'numberOfWorker': 'Number of Worker',
  'addPromoMoreThanOneWorker': 'Add promo more than one worker',
  'recapRequest': 'Recap Request',
  'weeks': 'Weekly',
  'packDetails': 'Pack Details',
  'monthly': 'Monthly',
  'morning': 'Morning',
  'afternoon': 'Afternoon',
  'failedToLoadData': 'Failed to load data',
  'noData': 'No Data Found',
  'pay': 'Pay',
  'servicePrice': 'Service Price Without TAX',
  'finalPriceDetails': 'Final Price Details',
  'amountToPaid': 'Amount to be paid',
  'totalValue': 'The total value',
  'valueAddedTax': 'Value Added TAX',
  'finalPricing': 'Final Pricing',
  'contractCreated': 'Contract Was Created Successfully',
  'finalPayment': 'Final Payment',
  'termsAndConditions': 'Terms and Conditions',
  'contactUsVia': 'Contact Us Via',
  'close': 'Close',
  'requiredNationality': 'The Required Nationality',
  'deliveryMethod': 'Delivery Method',
  'deliveryTime': 'Delivery Time',
  'listAvailableWorker': 'List of Available Worker',
  'fromBranch': 'From the Branch',
  'delivery': 'Delivery',
  'awaitingResult': 'Awaiting result...',
  'months': 'Months',
  'week': 'Week',
  'month': 'Month',
  'backToLogin': 'Back to Login',
  'agreeTermsAndConditions': 'Agree to the',
  'address': 'Address',
  'branchPhoneNumber': 'Branch Phone Number',
  'phoneNumber': 'Phone Number',
  'workingDays': 'Working Days',
  'workingTime': 'Working Time',
  'choose': 'Choose',
  'rs': 'RS',
  'gained': 'Saving',
  'cv': 'Curriculum Vitae',
  'listNotifications': 'Notifications List',
  'news': 'News',
  'helpCenter': 'Najda Help Center',
  'selectedWorkSuccess': 'The worker has been selected successfully',
  'complaints': 'Complaints',
  'generalTopics': 'General topics',
  'changeLanguage': 'Change the language',
  'notificationEmpty': 'Notifications list is empty',
  'morningTime': 'Morning',
  'afternoonTime': 'Afternoon',
  'changePassword': 'Change Password',
  'resetPassword': 'Reset Password',
  'muslim': 'Muslim',
  'muslimFemale': 'Muslim',
  'notMuslim': 'Not a Muslim',
  'confirmed': 'Confirmed',
  'chooseAddressOnMap': 'Choose a location on the map',
  'chooseAddressOnMapEdit': 'Choose a location on the map',
  'chooseBranchAddressOnMap':
      'To confirm , Please Press on the branch Location on the Map',
  'errorAddressUsed':
      'You can\'t delete an address because it is already used in the contract',
  'alertConfirmLogout': 'Are you sure you want to logout?',
  'alertConfirmRemoveAccount':
      "Attention please , this option will delete all data from application permanently ,\nand you can't roll back again",
  'frequentlyQuestions': 'Frequently Asked Questions',
  'contactUs': 'Contact Us',
  'contactUsTXt':
      'We are happy to provide our services to you\nYou can contact us through our website',
  'privacyPolicy': 'Privacy Policy',
  'evaluationInStore': 'Application evaluation In store',
  'shareTheApp': 'Share the App',
  'send': 'Send',
  'topic': 'Topic',
  'topicIsRequired': 'Topic is Required',
  'message': 'Please Write Your Message',
  'addNewComplaint': 'Add a New Complaint',
  'complaintsListEmpty': 'The list of complaints is empty',
  'complaintSubject': 'Subject of the complaint',
  'subjectComplaintIsRequired': 'The subject of the complaint is required',
  'typeComplaint': 'Type of complaint',
  'typeComplaintsIsRequired': 'the Type of complaint is required',
  'complaint': 'Complaint',
  'complaintsIsRequired': 'The content of complaint is required',
  'complaintDetails': 'Complaint details',
  'favoriteWorkers': 'Favorite workers',
  'emptyFavoriteWorkers': 'Favorite workers are empty',
  'branchAddress': 'Branch Address',
  'failureCreatedContract': 'Failed to create contract',
  'rescheduleDone': 'The appointment has been successfully rescheduled',
  'failureLoadedJobList': 'Failed to load the job list',
  'activateTheAccount': 'Activate the Account',
  'weight': 'Weight',
  'height': 'Height',
  'job': 'Job',
  'selectWorkerError': 'Please make sure to choose the worker',
  'selectPeriodError': 'Please make sure to choose the period',
  'chooseEmployee': 'Choose worker',
  'previousPlace': 'Previous workplace',
  'skills': 'Skills',
  'noPriceList': 'No price was found',
  'contractSaved': 'Save your order',
  'saveAndCallYou':
      'Save your request and you will be notified when the service is available',
  'payAndCreate': 'Pay and create contract',
  'serviceIn7Days':
      'The service will be provided within 7 days. In the event that the worker is not provided, the full amount will be refunded',
  'errorFetchingPriceList': 'Error occurred when fetching prices',
  'noWorkerFound':
      'To impose human cadres. The opportunity to have the opportunity to get the earliest available opportunity will be at another time. Would you like to have the opportunity to register in the contract? The service will be provided within 7 days or make your announcement if the service is available',
  'errorFetchingWorkersList':
      'Error occurred when fetching available workers list. Please try again.',
  'youCantAddAddress':
      'We apologize for serving you. The chosen location is outside the geographical coverage of our services at the present time.',
  'downloadPdf': 'Download Contract',
  'downloadInvoices': 'Download Invoice',
  'downloadAttachPdf': 'Download',
  'deliveryState': 'Delivery State',
  'pickupState': 'Pick up State',
  'orderReceivedDelivery': 'Order Received',
  'checkoutDelivery': 'Out for delivery',
  'checkout': 'Check out',
  'from': 'from',
  'to': 'to',
  'quesOneTxt':
      'Do you mind showing our agency application before receiving the maid?',
  'quesTwoTxt':
      'Is there any person at home with or suspected of having Covid-19 virus?',
  'quesThreeTxt':
      'Are there elderly people over 65 years old at home? Or a person suffering from respiratory diseases or chronic diseases?',
  'doneDelivery': 'Done',
  'orderReceivedPickup': 'Order Received',
  'readyPickup': 'Ready for pick up',
  'donePickup': 'Delivered',
  'agree': 'Agree',
  'failedToLoadNotification': 'Failed to load Notification List',
  'deleteNotificationMsg': 'Are you sure you want to delete notification ?',
  'failDeleteNotification': 'Failed to delete notification',
  'successDeleteNotification': 'Notification Deleted Successfully',
  'failedToLoadListOfComplaint': 'Failed to load list of complaints',
  'complaintSuccessDeleted': 'Complaint Successfully deleted',
  'failDeleteComplaint': 'Failed to delete complaint',
  'failAddingComplaint': 'Failed to add complaint',
  'successAddingComplaint': 'Complaint Successfully Added',
  'deleteComplaintMsg': 'Are you sure you want to delete complaint ?',
  'failedToLoadDetailsOfComplaint': 'Failed to load details of complaint',
  'failedLoadFrequentlyQuestion': 'Failed to load frequently question',
  'emptyFrequentlyQuestion': 'Frequently question is empty',
  'changeWorker': 'Change Worker',
  'failedSendRequestStaffReplacement':
      'Failed to Send the Request of Staff Replacement',
  'failedToLoadListOfAvailableWorker':
      'Failed to load list of available worker',
  'emptyListOfAvailableWorker': 'The list of available worker is empty',
  'successfullySentRequestOfChangeWorker':
      'Successfully Sent request of change worker',
  'deliveryChangeWorker': 'Delivery',
  'successCanceledContract': 'Successfully sending request to cancel contract',
  'failureCanceledContract': 'Failure canceled contract',
  'successSponsorshipTransferContract':
      'Successfully sending request to sponsorship transfer contract',
  'failureSponsorshipTransferContract':
      'Failure sending request to sponsorship transfer contract',
  'reasonsCancelContract': 'Reasons cancel contract',
  'reasonsSponsorshipTransferContract':
      'Reasons of sponsorship transfer contract',
  'reasons': 'Reasons',
  'questionSuspensionPeriod': 'What is the suspension period?',
  'pleaseChooseSuspensionPeriod':
      'Please choose the contract suspension period',
  'successSendRequestFreezeContract':
      'successfully Sent request for freeze contract',
  'failToFreezeContract': 'Fail to send request for freeze contract',
  'listPackages': 'List of packages',
  'failedToLoadListPackages': 'Failed to load list of package',
  'dependsOnTheRequest': 'Depends on the request',
  'detailsVisitsWithoutPackage':
      'In detail, the method of reserving the human staff for the visiting system',
  'visit': 'visit',
  'dateBeforeFreeze': 'Date Before Freeze',
  'visitsAfterFreeze': 'Visits After Freeze',
  'dateAfterFreeze': 'Date After Freeze',
  'visitDays': 'Visiting days',
  'cic': 'CIC',
  'cicAndPhoneMissing':
      'CIC And Phone Are Missing, please select one and add it\'s value',
  'successContactUs': 'Your message has been sent successfully',
  'failedContactUs':
      'Error occurred while sending your message. Please try again.',
  'emptyNewsList': 'News list is empty',
  'failedToLoadListOfNews': 'Failed to load list of news',
  'failedToLoadTermsAndConditions': 'Failed to load terms and conditions',
  'failedToLoadPrivacyPolicy': 'Failed to load privacy policy',
  'renewContract': 'renew Contract',
  'renewContractSameRequest': 'Contract renewal with the same requests',
  'renewContractDifferentRequest':
      'Contract renewal with the different requests',
  'failUpdatingContract': 'Failed to update contract',
  'failConfirmContract': 'Failed to confirm contract',
  'successUpdatingContract': 'successfully updating contract',
  'visitor': 'visitor',
  'addressMustHaveAccount': 'You must have an account to add an address',
  'logIntoYourAccount': 'Log into your account',
  'haveAccountToBookAHuman':
      'You must have an account to book a human cadre for the resident system',
  'haveAccountToViewListContract':
      'You must have an account to view the list of your contracts',
  'haveAccountToViewListNotification':
      'You must have an account to view the notifications list',
  'haveAccountToViewListProfile':
      'You must have an account to view your profile',
  'identityNumberShouldContainTenCharacters':
      'ID number should contain 10 characters',
  'portfolio': 'Portfolio',
  'failedToLoadPortfolio': 'Failed to load portfolio',
  'stock': 'Your balance with Najda',
  'stock2': 'Amount to be paid',
  'visitTime': 'Visit time',
  'visitingStatus': 'Visiting status',
  'worker': 'Worker',
  'addEvaluation': 'Evaluate',
  'addToFavorites': 'Add to favorites',
  'rescheduleAppointment': 'Reschedule the appointment',
  'dedicateVisit': 'Dedicate a visit',
  'rate': 'Evaluate',
  'confirm': 'Confirm',
  'dedicate': 'Dedicate',
  'currentAppointment': 'Current appointment',
  'currentAppointmentDialog': 'Not available  appointment',
  'newAppointment': 'New appointment',
  'newPeriod': 'New Period',
  'daysNewAppointment': 'New appointment',
  'actionDone': 'Done',
  'internetNotFound': 'You\'re offline, Check your connection and try again',
  'emptyDate': 'Please make sure to choose a date.',
  'cancelled': 'cancelled',
  'houseHold': 'Household employee',
  'draft': 'Draft',
  'draftRequest': 'Draft',
  'draftMission': 'Draft',
  'confirmedRequest': 'Confirmed',
  'refusedRequest': 'Refused',
  'failedToLoadRequestList': 'failed to load request list',
  'requestListIsEmpty': 'request list is empty',
  'myRequests': 'My Requests',
  'requestNumber': 'Request Number',
  'noEmployee': 'There is no available employee in this date',
  'capacityFull': 'The capacity is full in this day',
  'frozen': 'Frozen',
  'priceDetails': 'Price Details',
  'inProgressCancel': 'Cancellation is in progress',
  'inProgressSponsorship': 'Sponsorship is in progress',
  'inProgressFreeze': 'Freeze is in progress',
  'inProgressChangeEmployee': 'Change employee is in progress',
  'favouriteWorkerSuccessfullyDeleted': 'Favorite worker successfully deleted',
  'deleteFavoriteMsg': 'Are you sure you wan t to delete your favorite worker',
  'failedAction': 'Failed',
  'confirmation': 'Confirmation',
  'serialNumber': 'Serial Number',
  'bankName': 'Bank name',
  'bankAccountNumber': 'Bank account number',
  'bankNameRequired': 'Bank name required',
  'bankAccountNumberRequired': 'Bank account number required',
  'transferToBankAccount': 'Transfer to bank account',
  'transferToAccount': 'Transfer to account',
  'failToSendTransferToBankAccount':
      'Failed transfer your money to your a bank account',
  'successTransferToBankAccount':
      'successfully transfer your money to your bank account',
  'youCannotReschedule': 'You can not schedule the visit',
  'youCanSchedule': 'You can schedule',
  'cannotTrackingStaff':
      'You can t track staff you can contact he with number phone',
  'failedToLoad': 'Failed to load map',
  'paymentPage': 'Payment page',
  'login': 'Login',
  'logout': 'Logout',
  'pleaseSelectLocation':
      'Please select the location you will receive the service in it.',
  'gotoContractPage': 'Go to contract details',
  'age': 'age',
  'approved': 'Approved',
  'review': 'Review',
  'costSelectedWorker': 'Cost :',
  'warning': 'Warning',
  'favorite': 'Favorite',
  'wallet': 'Wallet',
  'currentCredit': 'Current Credit',
  'expiryDate': 'Expires in',
  'favList': 'Favourite List',
  'remove': 'Remove',
  'noFavItem': 'No Favourite Item',
  'confirmRemoveEmployee':
      'Are You Sure You Want To Delete this Employee From Favourite List?',
  'reload': 'Reload',
  'noSlider': 'No Sliders found',
  'contractNum': 'Contract Number',
  'viewContract': 'View Contract',
  'employee': 'Employee',
  'contactToDeliver': 'We will contact you to process your delivery request.',
  'rescheduleCosts': 'The rescheduling will cost',
  'rateApp': 'Rate the app in the store',
  'enterUsername': 'Enter your username ',
  'completeProfile': 'Complete Profile',
  'years': 'years',
  'amount': 'Amount',
  'pleaseEnterAmount': 'Please Enter The Amount',
  'visitsMenu': 'Visits List',
  'homeWorker': 'Home Worker',
  'maxNumValidVisits':
      'The maximum number of visits has been reached. Please uncheck visits and select again',
  'notAvaVisits': 'Unavailable Visits',
  'avaVisits': 'Available Visits',
  'addressPermission':
      'the permission to access to location and GPS services was not granted',
  'newDates': 'New Dates',
  'success': 'Success',
  'freezeRescheduleNote': 'Number of visits that would be rescheduled:',
  'freezeStartDate': 'Freeze Start Date',
  'freezeEndDate': 'Freeze End Date',
  'paymentFailed': 'Sorry your payment has been failed',
  'onBoarding1':
      'Welcome to Najda, the comprehensive solution for manpower services in the Kingdom of Saudi Arabia',
  'onBoarding2':
      'Efficiency and attention to attract trained and qualified workforce to meet all your needs',
  'onBoarding3': 'Choose the right worker for you and your family',
  'onBoarding4':
      'Ease of managing your orders and controlling contracts from one place',
  'visitState': 'Visit State',
  'active': 'Active',
  'favoriteWorkerAdded': 'Worker added to favorite list successfully!',
  'name': 'Name',
  'confirmToRemoveWorker1': 'Are you sure you want to remove',
  'confirmToRemoveWorker2': 'from your favorite list?',
  'unassigned': 'Unassigned',
  'enterOTP': 'Please enter the OTP sent to you',
  'min': 'min',
  'sec': 'sec',
  'pleaseSelectImage': 'Please select an image',
  'rateWorkerAdded': 'Rate added to Worker successfully!',
  'noContracts': 'No contracts created yet, Start now and add yours!',
  'sureToCancelContract': 'Are you sure you want to cancel your contract?',
  'pleaseWriteReasons':
      'Please write the reason why you want to cancel your contract.',
  'news_not_found': 'No News Available',
  'cancel_text_1':
      'In the event of canceling the contract, an administrative fee of',
  'cancel_text_2': 'will be deducted for each visit remaining in the contract.',
  'cancel_text_3': 'the number of visits remaining is',
  'cancel_text_4': 'and therefore the cancellation fee is',
  'cancel_text_5': 'The amount of',
  'cancel_text_6': 'will be refunded to your wallet within the application',
  'cancel_request': 'Cancel Request',
  'confirm_cancel_sms':
      'Please confirm the cancellation request by entering the verification code sent to your phone.',
  'unknownCancelDetails': 'Cancellation fee is unknown.',
  'refused': 'Refused',
  'arrived': 'Arrived',
  'get_in': 'Start get-in',
  'reward_error': 'Bank reward can not detected!',
  'number_not_found': 'number not found!',
  'un_authorized_message':
      "Your Token is expired, we will redirect you to login screen",
  'indonesia': 'Indonesia',
  'ethiopia': 'Ethiopia',
  'uganda': 'Uganda',
  'kenya': 'Kenya',
  'hours': 'hours',
  'for': 'for',
  'promoCodeTxtNotFound': 'OTP does not exist',
  'promoCodeAmountNotFound': 'promo code amount not found',
  'notification': 'Notification',
  'remove_user':'Remove Account'
};
